# Generated by Django 4.2.2 on 2023-07-07 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_seller', '0018_initial'),
        ('app_bayur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quntity', models.IntegerField(default=0)),
                ('product_color', models.CharField(max_length=50)),
                ('product_size', models.CharField(max_length=50)),
                ('Bayer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_bayur.add_user')),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_seller.listing_data')),
            ],
        ),
    ]
