# Generated by Django 4.2.2 on 2023-07-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bayur', '0003_cart_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkout_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_no', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=1000)),
                ('Country', models.CharField(max_length=50)),
            ],
        ),
    ]
