# Generated by Django 4.2.2 on 2023-07-12 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_bayur', '0004_checkout_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout_detail',
            name='bayer_detials',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_bayur.add_user'),
        ),
    ]
