# Generated by Django 4.2.2 on 2023-07-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bayur', '0006_checkout_detail_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout_detail',
            name='order_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
