# Generated by Django 4.2.2 on 2023-07-14 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bayur', '0007_alter_checkout_detail_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Bayer_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='Product_id',
        ),
        migrations.RemoveField(
            model_name='checkout_detail',
            name='bayer_detials',
        ),
        migrations.DeleteModel(
            name='Add_user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='checkout_detail',
        ),
    ]
