# Generated by Django 4.2.2 on 2023-07-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bayur', '0009_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout_detail',
            name='email',
            field=models.EmailField(max_length=20),
        ),
    ]
