# Generated by Django 4.2.2 on 2023-07-15 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_bayur', '0010_alter_checkout_detail_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Details_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_bayur.checkout_detail'),
        ),
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
