# Generated by Django 4.2.2 on 2023-07-02 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seller', '0003_alter_seller_data_propic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing_data',
            name='P_Prise',
        ),
        migrations.AddField(
            model_name='listing_data',
            name='Listing_immage',
            field=models.FileField(default='Listing/abc.jpg', upload_to='Listing/'),
        ),
        migrations.AddField(
            model_name='listing_data',
            name='P_Price',
            field=models.IntegerField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='listing_data',
            name='P_Description',
            field=models.TextField(max_length=500),
        ),
    ]
