# Generated by Django 4.2.2 on 2023-07-03 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_seller', '0004_remove_listing_data_p_prise_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing_data',
        ),
        migrations.DeleteModel(
            name='Seller_data',
        ),
    ]
