# Generated by Django 4.2.2 on 2023-07-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seller', '0007_remove_listing_data_p_tex_ammount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_data',
            name='Mobile_No',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='seller_data',
            name='firstname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='seller_data',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
