# Generated by Django 4.2.2 on 2023-07-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seller', '0008_alter_seller_data_mobile_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing_data',
            name='P_Price',
            field=models.CharField(max_length=50),
        ),
    ]
