# Generated by Django 4.2.2 on 2023-07-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seller', '0010_alter_listing_data_p_quntity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing_data',
            name='P_Description',
            field=models.CharField(max_length=500),
        ),
    ]
