# Generated by Django 4.2.2 on 2023-07-04 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_seller', '0011_alter_listing_data_p_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing_data',
            old_name='P_fabric',
            new_name='P_size',
        ),
        migrations.RemoveField(
            model_name='listing_data',
            name='P_id',
        ),
    ]
