# Generated by Django 4.2.2 on 2023-07-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seller', '0012_rename_p_fabric_listing_data_p_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing_data',
            name='P_Price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='listing_data',
            name='P_size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='XS', max_length=100),
        ),
    ]
