# Generated by Django 4.2.2 on 2023-07-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seller', '0013_alter_listing_data_p_price_alter_listing_data_p_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing_data',
            name='P_Price',
            field=models.CharField(max_length=100),
        ),
    ]
