# Generated by Django 4.2.2 on 2023-07-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seller', '0014_alter_listing_data_p_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing_data',
            name='P_size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=100),
        ),
    ]
