# Generated by Django 4.0 on 2023-07-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seller', '0015_alter_listing_data_p_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing_data',
            name='P_size',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=100),
        ),
    ]
