# Generated by Django 4.2.2 on 2023-07-06 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_seller', '0016_alter_listing_data_p_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing_data',
        ),
        migrations.DeleteModel(
            name='Seller_data',
        ),
    ]
