# Generated by Django 4.2.2 on 2023-07-15 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_seller', '0019_alter_listing_data_p_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing_data',
            name='seller_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_seller.seller_data'),
        ),
    ]
