# Generated by Django 4.2.2 on 2023-07-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seller', '0020_alter_listing_data_seller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing_data',
            name='Categary',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
