# Generated by Django 4.2.2 on 2023-07-18 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_seller', '0021_listing_data_categary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing_data',
            old_name='Categary',
            new_name='P_Categary',
        ),
    ]
